server:
  port: 8082


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.14.21:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.team.pojo


#showSql
logging:
  config:classpath:log4j2-spring.xml
